from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CalculatorViewSet # Assuming you have a CalculatorViewSet in your views.py

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'', CalculatorViewSet, basename='calculation') # 'calculations' will be the base URL for your calculator operations

# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('', include(router.urls)), # This includes all the URLs generated by the router
]